import type { DepartmentCode, TaskAutoComplete, TaskGroup, TaskTriggerEvent, TaskTriggerType } from "@prisma/client";

// Шаблон «Лекция с гостем» по регламенту мероприятий клуба и чек-листам отделов.
// Сроки — дни относительно даты мероприятия (для EVENT — дни после события).
// Задачи дня мероприятия несут тайминг: минуты от начала и подпись шага.
// Версия шаблона: при изменении увеличьте LECTURE_TEMPLATE_VERSION — сид заменит шаблон в базе.
export const LECTURE_TEMPLATE_VERSION = "2";

export type LectureTemplateRow = {
  title: string;
  department: DepartmentCode | null;
  triggerType: TaskTriggerType;
  offsetDays: number | null;
  triggerEvent: TaskTriggerEvent | null;
  required: boolean;
  needsTwoAssignees: boolean;
  firesTrigger: TaskTriggerEvent | null;
  autoComplete: TaskAutoComplete | null;
  group: TaskGroup;
  sortOrder: number;
  dayOffsetMinutes: number | null;
  dayTimeLabel: string | null;
};

export const LECTURE_TEMPLATE: LectureTemplateRow[] = [
  // --- До мероприятия: окно дат → ЦБ → дата → аудитория, пиар, съёмка
  {
    title: "Выбрать гостя из базы и написать ему",
    department: "GUESTS",
    triggerType: "DATE_OFFSET",
    offsetDays: -45,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 10,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Согласовать с гостем окно из 10 дней, предупредить про проверку ЦБ",
    department: "GUESTS",
    triggerType: "DATE_OFFSET",
    offsetDays: -45,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 20,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Завести карточку гостя в чате: кто, тема, окно дат",
    department: "GUESTS",
    triggerType: "DATE_OFFSET",
    offsetDays: -45,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 30,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Подать заявку в ЦБ на проверку гостя",
    department: "SECURITY",
    triggerType: "DATE_OFFSET",
    offsetDays: -30,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: true,
    firesTrigger: "SECURITY_SUBMITTED",
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 40,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Получить ответ ЦБ и в тот же день написать в чат",
    department: "SECURITY",
    triggerType: "EVENT",
    offsetDays: 7,
    triggerEvent: "SECURITY_SUBMITTED",
    required: true,
    needsTwoAssignees: true,
    firesTrigger: "SECURITY_ANSWERED",
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 50,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Зафиксировать дату и время после ответа ЦБ, написать в чат",
    department: "GUESTS",
    triggerType: "DATE_OFFSET",
    offsetDays: -21,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: "DATE_FIXED",
    group: "BEFORE",
    sortOrder: 60,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Выбрать аудиторию вместе в чате — из списка 15–20, не единолично",
    department: "PR",
    triggerType: "EVENT",
    offsetDays: 0,
    triggerEvent: "DATE_FIXED",
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 70,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Подать служебку на аудиторию",
    department: "PR",
    triggerType: "EVENT",
    offsetDays: 0,
    triggerEvent: "DATE_FIXED",
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 80,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "План анонсов по мероприятию",
    department: "PR",
    triggerType: "EVENT",
    offsetDays: 0,
    triggerEvent: "DATE_FIXED",
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 90,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "План съёмок по мероприятию",
    department: "CONTENT",
    triggerType: "EVENT",
    offsetDays: 0,
    triggerEvent: "DATE_FIXED",
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 100,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Анонсный ролик после подтверждения гостя",
    department: "CONTENT",
    triggerType: "EVENT",
    offsetDays: 3,
    triggerEvent: "SECURITY_ANSWERED",
    required: false,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 110,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Подтверждение аудитории — в чат",
    department: "PR",
    triggerType: "DATE_OFFSET",
    offsetDays: -17,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 120,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Пост №1: открыть регистрацию для внешних гостей",
    department: "PR",
    triggerType: "DATE_OFFSET",
    offsetDays: -14,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 130,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Афиша: сделать и собрать правки в отделе",
    department: "PR",
    triggerType: "DATE_OFFSET",
    offsetDays: -12,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 140,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Согласовать афишу и пост с гостем, спросить про питч-сессию (7 минут)",
    department: "GUESTS",
    triggerType: "DATE_OFFSET",
    offsetDays: -10,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 150,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Пост №2: афиша + «регистрация закрывается через день»",
    department: "PR",
    triggerType: "DATE_OFFSET",
    offsetDays: -7,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 160,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Репосты: старостат, СНО, кейс-клуб, другие вузы",
    department: "PR",
    triggerType: "DATE_OFFSET",
    offsetDays: -7,
    triggerEvent: null,
    required: false,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 170,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Закрыть регистрацию",
    department: "PR",
    triggerType: "DATE_OFFSET",
    offsetDays: -6,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: "REGISTRATION_CLOSED",
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 180,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Список внешних гостей — в ЦБ сразу после закрытия регистрации",
    department: "SECURITY",
    triggerType: "EVENT",
    offsetDays: 0,
    triggerEvent: "REGISTRATION_CLOSED",
    required: true,
    needsTwoAssignees: true,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 190,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Пост №3 (последний)",
    department: "PR",
    triggerType: "DATE_OFFSET",
    offsetDays: -3,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 200,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Лично забрать пропуска в ЦБ",
    department: "SECURITY",
    triggerType: "DATE_OFFSET",
    offsetDays: -3,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: true,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 210,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Позвать людей вживую — каждый зовёт своих",
    department: null,
    triggerType: "DATE_OFFSET",
    offsetDays: -3,
    triggerEvent: null,
    required: false,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 220,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Стоп-лист: все обязательные задачи закрыты",
    department: null,
    triggerType: "DATE_OFFSET",
    offsetDays: -2,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 230,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Забрать оборудование накануне",
    department: "STAGE",
    triggerType: "DATE_OFFSET",
    offsetDays: -1,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: true,
    firesTrigger: null,
    autoComplete: null,
    group: "BEFORE",
    sortOrder: 240,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  // --- День мероприятия — по сценарию
  {
    title: "Аудитория открыта, проектор и звук работают, презентация загружена",
    department: "STAGE",
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: true,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 300,
    dayOffsetMinutes: -120,
    dayTimeLabel: "−2 часа"
  },
  {
    title: "Два волонтёра на посту охраны со списком",
    department: "STAGE",
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: true,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 310,
    dayOffsetMinutes: -40,
    dayTimeLabel: "−40 минут"
  },
  {
    title: "Встретить гостя — один человек",
    department: "GUESTS",
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 320,
    dayOffsetMinutes: -20,
    dayTimeLabel: "−20 минут"
  },
  {
    title: "Открытие, представление гостя",
    department: null,
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 330,
    dayOffsetMinutes: 0,
    dayTimeLabel: "0:00"
  },
  {
    title: "Съёмка: зал, спикер, реакция",
    department: "CONTENT",
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 340,
    dayOffsetMinutes: 0,
    dayTimeLabel: "0:00"
  },
  {
    title: "Один организатор в конце зала весь тайминг",
    department: "STAGE",
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 350,
    dayOffsetMinutes: 0,
    dayTimeLabel: "всё мероприятие"
  },
  {
    title: "Вопросы: первые — из заготовленного списка, дальше зал",
    department: null,
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 360,
    dayOffsetMinutes: null,
    dayTimeLabel: "после выступления"
  },
  {
    title: "Питч-сессия 7 минут по таймеру (если согласована)",
    department: null,
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: false,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 370,
    dayOffsetMinutes: null,
    dayTimeLabel: "финал"
  },
  {
    title: "Общее фото при полном зале",
    department: "CONTENT",
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 380,
    dayOffsetMinutes: null,
    dayTimeLabel: "финал"
  },
  {
    title: "Гостя уводят — сначала фото, потом уводим",
    department: "GUESTS",
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 390,
    dayOffsetMinutes: null,
    dayTimeLabel: "сразу после"
  },
  {
    title: "Интервью с гостем",
    department: "CONTENT",
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 400,
    dayOffsetMinutes: null,
    dayTimeLabel: "сразу после"
  },
  {
    title: "Собрать и вернуть технику",
    department: "STAGE",
    triggerType: "DATE_OFFSET",
    offsetDays: 0,
    triggerEvent: null,
    required: true,
    needsTwoAssignees: true,
    firesTrigger: null,
    autoComplete: null,
    group: "EVENT_DAY",
    sortOrder: 410,
    dayOffsetMinutes: null,
    dayTimeLabel: "после"
  },
  // --- После: через сутки монтаж, через 3 дня фото, пост-отчёт, спасибо гостю
  {
    title: "Материал на монтаж — в течение суток",
    department: "CONTENT",
    triggerType: "EVENT",
    offsetDays: 1,
    triggerEvent: "EVENT_DONE",
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "AFTER",
    sortOrder: 500,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Фото и видео: ссылка на фотоотчёт в карточке",
    department: "CONTENT",
    triggerType: "EVENT",
    offsetDays: 3,
    triggerEvent: "EVENT_DONE",
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: "PHOTO_REPORT_ATTACHED",
    group: "AFTER",
    sortOrder: 510,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Пост-отчёт",
    department: "PR",
    triggerType: "EVENT",
    offsetDays: 3,
    triggerEvent: "EVENT_DONE",
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "AFTER",
    sortOrder: 520,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Поблагодарить гостя",
    department: "GUESTS",
    triggerType: "EVENT",
    offsetDays: 3,
    triggerEvent: "EVENT_DONE",
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: null,
    group: "AFTER",
    sortOrder: 530,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  },
  {
    title: "Ретро заполнено, посещаемость внесена",
    department: null,
    triggerType: "EVENT",
    offsetDays: 3,
    triggerEvent: "EVENT_DONE",
    required: true,
    needsTwoAssignees: false,
    firesTrigger: null,
    autoComplete: "RETRO_SAVED",
    group: "AFTER",
    sortOrder: 540,
    dayOffsetMinutes: null,
    dayTimeLabel: null
  }
];
